import styles from "./Project.module.css";

export default function ProjectDizcord() {
  return (
    <div className={styles.ProjectDizcord}>
      Projects
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
      <div>ProjectDizcord</div>
    </div>
  );
}
